//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RatnaKiran.rc
//
#define IDD_ABOUT_DIALOG                100
#define IDR_MAINFRAME                   101
#define IDR_RATNAKTYPE                  102
#define IDB_STATE_IMAGE                 200
#define IDB_BLACK_IMAGE                 201
#define IDB_WHITE_IMAGE                 202
#define IDR_PREVIEW                     203
#define IDB_PRINT                       204
#define IDB_PREVIOUS                    205
#define IDB_NEXT                        206
#define IDB_CANCEL                      207
#define IDB_PRINT_THIS_PAGE             208
#define IDD_MARKED_VALUE_FORMULA_DIALOG_KUNDAN 301
#define IDD_ADD_DIALOG_STOCK            1000
#define IDD_ADD_DIALOG_KUNDAN           1001
#define IDD_ADD_DIALOG_EXPORT           1002
#define ID_SET_SAVE                     1003
#define ID_SET_CANCEL                   1004
#define ID_ITEM_ADD                     1005
#define ID_ITEM_DELETE                  1006
#define ID_SET_DESCRIPTION_LIST         1007
#define ID_ITEM_DESCRIPTION_LIST        1008
#define ID_DIAMOND_DETAILS              1009
#define ID_STONE_DETAILS                1010
#define ID_ITEM_CHANGE_IMAGE            1011
#define ID_ITEM_REMOVE_IMAGE            1012
#define ID_MARKED_VALUES                1014
#define ID_OLD_SERIALS                  1015
#define IDC_ITEM_TABS                   1016
#define IDC_SET_PRODUCTID               1017
#define IDC_SET_DESCRIPTION             1018
#define IDC_UNSOLD_PIECE_COUNT          1019
#define IDC_ITEM_PRODUCTID              1020
#define IDC_ITEM_DESCRIPTION            1021
#define IDC_DIAMOND_WEIGHT              1022
#define IDC_DIAMOND_RATE                1023
#define IDC_DIAMOND_MARKED_RATE         1024
#define IDC_DIAMOND_VALUE               1025
#define IDC_DIAMOND_MARKED_VALUE        1026
#define IDC_STONE_WEIGHT                1027
#define IDC_STONE_RATE                  1028
#define IDC_STONE_MARKED_RATE           1029
#define IDC_STONE_VALUE                 1030
#define IDC_STONE_MARKED_VALUE          1031
#define IDC_PEARL_WEIGHT                1032
#define IDC_PEARL_RATE                  1033
#define IDC_PEARL_MARKED_RATE           1034
#define IDC_PEARL_VALUE                 1035
#define IDC_PEARL_MARKED_VALUE          1036
#define IDC_DIAMOND_CLARITY             1037
#define IDC_NET_WEIGHT                  1038
#define IDC_GOLD_VALUE                  1039
#define IDC_ITEM_PIECE_COUNT            1040
#define IDC_LABOUR_CHARGE               1041
#define IDC_MARKED_LABOUR_CHARGE        1042
#define IDC_OTHER_WEIGHT                1043
#define IDC_TOTAL_PRICE                 1046
#define IDC_TOTAL_MARKED_PRICE          1047
#define IDC_ITEM_PHOTO                  1048
#define IDC_IMAGE_FRAME                 1049
#define IDC_ITEM_SOLD                   1050
#define IDC_SOLD_COUNTRY                1051
#define IDC_ITEM_USE_NET_WEIGHT         1052
#define IDC_COSTING                     1052
#define IDC_SERIAL_NUMBER               1053
#define IDC_MARKED_COSTING              1053
#define IDD_STOCK_VIEW                  1100
#define IDD_APPENDLIST_DIALOG           1101
#define IDD_GENERIC_LIST_BOX_DIALOG     1102
#define IDC_LIST                        1103
#define IDC_TEXT                        1104
#define ID_BUTTON_1                     1105
#define ID_BUTTON_2                     1106
#define IDD_OPTION_DIALOG               1200
#define IDC_OPTION_PRINT                1201
#define IDC_OPTION_SAVEFILE             1202
#define IDD_DETAILS_DIALOG_EXPORT       1300
#define IDC_EXPORT_CONSIGNEE            1301
#define IDC_EXPORT_CONVERSION_RATE      1302
#define IDC_EXPORT_COUNTRY              1303
#define IDC_EXPORT_CURRENCY             1304
#define IDC_EXPORT_EXPORTER             1305
#define IDC_EXPORT_GOLD_RATE            1306
#define IDC_EXPORT_INVOICE              1307
#define IDC_EXPORT_USD_RATE             1308
#define IDC_FORMULAS_DIAMOND_RATE       1309
#define IDC_FORMULAS_PEARL_RATE         1310
#define IDC_FORMULAS_STONE_RATE         1311
#define IDC_FORMULAS_PRICE_QUOTE        1312
#define IDC_FORMULAS_VALUE_ADDED_LABOUR 1313
#define IDD_SHORTINVOICE_DETAILS        1400
#define IDC_EXPORTS_BUYER               1401
#define IDC_EXPORTS_EXPORTER_GR_NUMBER  1402
#define IDC_EXPORTS_GR_NUMBER           1403
#define IDC_EXPORTS_ORDER_NUMBER        1404
#define IDC_EXPORTS_PRECARRIAGE         1405
#define IDC_EXPORTS_PLACE_RECEIPT       1406
#define IDC_EXPORTS_TERMS               1407
#define IDC_EXPORTS_VESSEL              1408
#define IDD_MARKED_VALUE_FORMULA_DIALOG_STOCK 1500
#define IDC_FORMULAS_DIAMOND            1501
#define IDC_FORMULAS_PEARL              1502
#define IDC_FORMULAS_PRECIOUS_STONE     1503
#define IDC_FORMULAS_LABOUR             1504
#define IDC_FORMULAS_MARKED_PRICE       1505
#define IDD_DESCRIPTION_ADD_DIALOG      1600
#define IDC_NAME                        1601
#define IDC_PREFIX                      1602
#define IDC_NUMBER_OF_PIECES            1603
#define IDD_DETAILS_DIALOG_STOCK        1700
#define IDC_STOCK_GOLD_RATE             1701
#define IDD_DETAILS_DIALOG_KUNDAN       1800
#define IDC_KUNDAN_GOLD_RATE            1801
#define IDD_PROGRESS_DIALOG             1900
#define IDC_PROGRESS_BAR                1901
#define IDD_GENERIC_ONE_EDIT_DIALOG     2000
#define IDC_TITLE                       2001
#define IDC_ENTRY                       2002
#define IDD_GENERIC_TWO_EDIT_DIALOG     2100
#define IDC_TITLE_1                     2101
#define IDC_TITLE_2                     2102
#define IDC_ENTRY_1                     2103
#define IDC_ENTRY_2                     2104
#define IDD_MOVE_DIALOG                 2200
#define IDC_STOCK                       2201
#define IDC_EXPORT                      2202
#define IDC_KUNDAN                      2203
#define IDD_EXPORT_SERIALS_DIALOG       2300
#define IDC_TO                          2301
#define IDC_FROM                        2302
#define IDC_USE_OLD                     2303
#define IDC_USE_NEW                     2304
#define IDC_TAGNAME                     2305
#define IDC_TAGNAMES                    2306
#define IDC_STATIC_TAGNAME              2307
#define IDC_USE_PRODUCTID               2308
#define IDD_EDIT_PERMISSIONS            2400
#define IDC_TREE_DISALLOWED             2401
#define IDC_TREE_ALLOWED                2402
#define IDC_TO_RIGHT                    2403
#define IDC_TO_LEFT                     2404
#define IDD_ADD_USER_DIALOG             2501
#define IDC_USERNAMES                   2502
#define IDC_EDIT_1                      2503
#define IDC_FIRST_ENTRY                 2504
#define IDC_NEW_PASSWORD                2505
#define IDC_RECONFIRM_NEW_PASSWORD      2506
#define IDC_GROSS_WEIGHT                2604
#define IDC_PROGRESS_WORK               2610
#define IDC_FORMULAS_COSTING            2611
#define ID_TREE_CREATENEWSTOCKVOUCHER   32700
#define ID_TREE_CREATENEWEXPORTVOUCHER  32701
#define ID_TREE_CREATENEWKUNDANVOUCHER  32702
#define ID_TREE_DELETESELECTED          32703
#define ID_TREE_UPDATEINFORMATION       32704
#define ID_TREE_MARKITEMASSOLD_ONPRODUCTID 32705
#define ID_TREE_MARKITEMASSOLD_ONSERIALNUMBER 32706
#define ID_TREE_REALLOCATESERIALNUMBERS 32707
#define ID_TREE_DELETESOLDITEMS         32708
#define ID_TREE_QUERYSET_GROSS_WEIGHT   32709
#define ID_TREE_QUERYSET_ID             32710
#define ID_SET_ADDNEW                   32800
#define ID_SET_EDIT                     32801
#define ID_SET_DELETE_CURRENT           32802
#define ID_SET_DELETE_CHECKED           32803
#define ID_SET_DELETE_HIGHLIGHTED       32804
#define ID_SET_DELETECHECKED_HIGHLIGHTED 32805
#define ID_SET_MOVE_CREATENEW           32806
#define ID_SET_MOVE_ADDTOEXISTING       32807
#define ID_SET_SELECTALL                32808
#define ID_SET_SELECTHIGHLIGHTED        32809
#define ID_SET_UNSELECTALL              32810
#define ID_SET_UNSELECTHIGHLIGHTED      32811
#define ID_SET_CHANGEPRODUCTID          32812
#define ID_SET_RESETOLDSERIALS          32813

#define ID_REPORTS_STOCK_STOCKSREPORT_ACTUALS_ORIGINAL 32900
#define ID_REPORTS_STOCK_STOCKSREPORT_ACTUALS_SOLD 32901
#define ID_REPORTS_STOCK_STOCKSREPORT_ACTUALS_UNSOLD 32902
#define ID_REPORTS_STOCK_STOCKSREPORT_MARKED_ORIGINAL 32903
#define ID_REPORTS_STOCK_STOCKSREPORT_MARKED_SOLD 32904
#define ID_REPORTS_STOCK_STOCKSREPORT_MARKED_UNSOLD 32905
#define ID_REPORTS_STOCK_PRICEQUOTATION_ORIGINAL 32906
#define ID_REPORTS_STOCK_PRICEQUOTATION_SOLD 32907
#define ID_REPORTS_STOCK_PRICEQUOTATION_UNSOLD 32908
#define ID_REPORTS_STOCK_CHECKLIST_ORIGINAL 32909
#define ID_REPORTS_STOCK_CHECKLIST_SOLD 32910
#define ID_REPORTS_STOCK_CHECKLIST_UNSOLD 32911
#define ID_REPORTS_STOCK_TAGS           32912
#define ID_REPORTS_STOCK_PHOTOINVOICE_ORIGINAL 32913
#define ID_REPORTS_STOCK_PHOTOINVOICE_SOLD 32914
#define ID_REPORTS_STOCK_PHOTOINVOICE_UNSOLD 32915


#define ID_REPORTS_EXPORT_PACKAGELIST_ORIGINAL 32920
#define ID_REPORTS_EXPORT_PACKAGELIST_SOLD 32921
#define ID_REPORTS_EXPORT_PACKAGELIST_UNSOLD 32922
#define ID_REPORTS_EXPORT_SHORTINVOICE_ORIGINAL 32923
#define ID_REPORTS_EXPORT_SHORTINVOICE_SOLD 32924
#define ID_REPORTS_EXPORT_SHORTINVOICE_UNSOLD 32925
#define ID_REPORTS_EXPORT_PHOTOINVOICE_ORIGINAL 32926
#define ID_REPORTS_EXPORT_PHOTOINVOICE_SOLD 32927
#define ID_REPORTS_EXPORT_PHOTOINVOICE_UNSOLD 32928
#define ID_REPORTS_EXPORT_PRICEQUOTATION_ORIGINAL 32929
#define ID_REPORTS_EXPORT_PRICEQUOTATION_SOLD 32930
#define ID_REPORTS_EXPORT_PRICEQUOTATION_UNSOLD 32931
#define ID_REPORTS_EXPORT_CHECKLIST_ORIGINAL 32932
#define ID_REPORTS_EXPORT_CHECKLIST_SOLD 32933
#define ID_REPORTS_EXPORT_CHECKLIST_UNSOLD 32934
#define ID_REPORTS_EXPORT_TAGS          32935
#define ID_REPORTS_EXPORT_GRFORM        32936

#define ID_REPORTS_KUNDAN_STOCKSREPORT_ACTUALS_ORIGINAL 32940
#define ID_REPORTS_KUNDAN_STOCKSREPORT_ACTUALS_SOLD 32941
#define ID_REPORTS_KUNDAN_STOCKSREPORT_ACTUALS_UNSOLD 32942
#define ID_REPORTS_KUNDAN_STOCKSREPORT_MARKED_ORIGINAL 32943
#define ID_REPORTS_KUNDAN_STOCKSREPORT_MARKED_SOLD 32944
#define ID_REPORTS_KUNDAN_STOCKSREPORT_MARKED_UNSOLD 32945
#define ID_REPORTS_KUNDAN_CHECKLIST_ORIGINAL 32946
#define ID_REPORTS_KUNDAN_CHECKLIST_SOLD 32947
#define ID_REPORTS_KUNDAN_CHECKLIST_UNSOLD 32948
#define ID_REPORTS_KUNDAN_TAGS          32949

#define ID_REPORTS_CATALOGUE            32950
#define ID_USINGFOREXPORTS_NATIVECURRENCY 33001
#define ID_USINGFOREXPORTS_DOLLARUSD    33002
#define ID_SETTINGS_CHANGEFILEPATH      33003
#define ID_SETTINGS_UPDATEGOLDRATE      33004
#define ID_SETTINGS_MANAGEDESCRIPTIONDATABASE 33005
#define ID_SETTINGS_BACKUP              33006
#define ID_USER_ADD                     33008
#define ID_USER_DELETE                  33009
#define ID_USER_EDIT_PERM               33010
#define ID_USER_CHANGE_PASSWORD         33011
#define ID_PREVIOUS                     33101
#define ID_NEXT                         33102
#define ID_CANCEL                       33103
#define ID_PRINT                        33104
#define ID_TREE_IGNORESELECTED          34019

#define IDS_FILEPATH_SUFFIX             61205
#define IDS_REGISTRY_SECTION            61208
#define IDS_FILE_PATH                   61210
#define IDS_SHOW_ERRORS                 61211

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         34023
#define _APS_NEXT_CONTROL_VALUE         2613
#define _APS_NEXT_SYMED_VALUE           400
#endif
#endif
