//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ratnakiran.rc
//
#define ID_SET_CANCEL                   3
#define IDD_ABOUTBOX                    100
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_MAINFRAME                   128
#define IDR_RATNAKTYPE                  129
#define IDD_GENERIC_ONE_EDIT_DIALOG     130
#define IDD_GENERIC_TWO_EDIT_DIALOG     131
#define IDD_PROGRESS_DIALOG             132
#define IDB_BLACK_IMAGE                 133
#define IDB_STATE_IMAGE                 134
#define IDB_WHITE_IMAGE                 135
#define IDD_APPENDLIST_DIALOG           142
#define IDD_REPORT_OPTION_DIALOG        143
#define IDD_DETAILS_DIALOG_EXPORT       149
#define IDD_MARKED_VALUE_FORMULA_DIALOG 151
#define IDD_DESCRIPTION_ADD_DIALOG      153
#define IDD_ADD_DIALOG_EXPORT           156
#define IDD_DETAILS_DIALOG_STOCK        161
#define IDD_SHORTINVOICE_DETAILS        171
#define IDD_GENERIC_LIST_BOX_DIALOG     174
#define IDD_EXPORT_SERIALS_DIALOG       175
#define IDR_PREVIEW                     178
#define IDB_PRINT                       187
#define IDB_PREVIOUS                    191
#define IDB_NEXT                        192
#define IDB_CANCEL                      193
#define IDB_PRINT_THIS_PAGE             194
#define IDD_MOVE_OPTION_DIALOG          197
#define IDD_DETAILS_DIALOG_KUNDAN       200
#define IDD_STOCK_VIEW                  201
#define IDD_ADD_DIALOG_KUNDAN           202
#define IDD_ADD_DIALOG_STOCK            203
#define IDC_SET_PRODUCTID               1002
#define IDC_SET_DESCRIPTION             1003
#define IDC_ITEM_DESCRIPTION            1006
#define IDC_GROSS_WEIGHT                1007
#define IDC_NET_WEIGHT                  1008
#define IDC_ITEM_PIECE_COUNT            1009
#define IDC_GOLD_VALUE                  1010
#define IDC_RATE                        1011
#define IDC_DIAMOND_WEIGHT              1012
#define IDC_MARKED_RATE                 1012
#define IDC_DIAMOND_RATE                1013
#define IDC_UNSOLD_PIECE_COUNT          1014
#define ID_SET_SAVE                     1020
#define ID_ITEM_DELETE                  1021
#define ID_ITEM_ADD                     1022
#define ID_MARKED_VALUES                1027
#define IDC_ITEM_PRODUCTID              1028
#define IDC_PEARL_MARKED_VALUE          1029
#define IDC_LIST                        1030
#define IDC_OTHER_WEIGHT                1030
#define IDC_OPTION_PRINT                1031
#define IDC_TOTAL_PRICE                 1031
#define IDC_OPTION_SAVEFILE             1032
#define IDC_DIAMOND_VALUE               1032
#define IDC_DIAMOND_MARKED_VALUE        1033
#define IDC_LABOUR_CHARGE               1034
#define IDC_MARKED_LABOUR_CHARGE        1035
#define IDC_STONE_WEIGHT                1036
#define IDC_STONE_RATE                  1037
#define IDC_STONE_VALUE                 1038
#define IDC_STONE_MARKED_VALUE          1039
#define IDC_PEARL_WEIGHT                1040
#define IDC_PEARL_RATE                  1041
#define IDC_PEARL_VALUE                 1042
#define IDC_TOTAL_MARKED_PRICE          1043
#define IDC_ITEM_PHOTO                  1044
#define ID_OLD_SERIALS                  1045
#define IDC_SOLD_COUNTRY                1046
#define ID_ITEM_REMOVE_IMAGE            1047
#define IDC_ITEM_SOLD                   1048
#define IDC_ITEM_USE_NET_WEIGHT         1049
#define ID_ITEM_DUMP_IMAGE              1050
#define IDC_IMAGE_FRAME                 1051
#define ID_DIAMOND_DETAILS              1052
#define ID_STONE_DETAILS                1053
#define IDC_EXPORTS_CONSIGNEE           1055
#define IDC_EXPORTS_COUNTRY             1056
#define IDC_EXPORTS_INVOICE             1057
#define IDC_FORMULAS_DIAMOND            1058
#define IDC_EXPORTS_CURRENCY            1058
#define IDC_FORMULAS_STONE              1059
#define IDC_EXPORTS_CONVERSION_RATE     1059
#define IDC_NAME                        1060
#define IDC_FORMULAS_PEARL              1060
#define IDC_EXPORTS_GOLD_RATE           1060
#define IDC_PREFIX                      1061
#define IDC_FORMULAS_LABOUR             1061
#define IDC_EXPORTS_USD_RATE            1061
#define IDC_NUMBER_OF_PIECES            1062
#define IDC_FORMULAS_MARKED_PRICE       1062
#define ID_SET_DESCRIPTION_LIST         1062
#define ID_ITEM_DESCRIPTION_LIST        1063
#define IDC_FORMULAS_VALUE_ADDED_LABOUR 1066
#define IDC_FORMULAS_DIAMOND_RATE       1067
#define IDC_FORMULAS_PEARL_RATE         1068
#define IDC_FORMULAS_STONE_RATE         1069
#define IDC_ITEM_TABS                   1071
#define IDC_FORMULAS_PRICE_QUOTE        1072
#define IDC_PEARL_MARKED_RATE           1074
#define IDC_STONE_MARKED_RATE           1075
#define IDC_DIAMOND_MARKED_RATE         1076
#define IDC_SERIAL_NUMBER               1079
#define IDC_STOCK_GOLD_RATE             1080
#define IDC_PROGRESS_BAR                1082
#define IDC_EXPORTS_BUYER               1084
#define IDC_EXPORTS_EXPORTER_GR_NUMBER  1085
#define IDC_EXPORTS_ORDER_NUMBER        1086
#define IDC_EXPORTS_PRECARRIAGE         1087
#define IDC_EXPORTS_PLACE_RECEIPT       1088
#define IDC_EXPORTS_VESSEL              1089
#define IDC_ENTRY_1                     1090
#define IDC_EXPORTS_TERMS               1090
#define IDC_ENTRY_2                     1091
#define IDC_EXPORTS_GR_NUMBER           1091
#define IDC_ENTRY                       1092
#define IDC_TITLE_1                     1092
#define IDC_TITLE                       1093
#define IDC_TITLE_2                     1093
#define ID_BUTTON_1                     1093
#define ID_BUTTON_2                     1094
#define IDC_TEXT                        1095
#define IDC_EXPORTS_EXPORTER            1096
#define ID_ITEM_CHANGE_IMAGE            1097
#define IDC_FROM                        1099
#define IDC_TO                          1100
#define IDC_TAGNAME                     1101
#define IDC_USE_OLD                     1102
#define IDC_USE_NEW                     1103
#define IDC_STOCK                       1117
#define IDC_EXPORT                      1118
#define IDC_KUNDAN                      1119
#define IDC_KUNDAN_GOLD_RATE            1121
#define IDC_STOCK_PRICE_QUOTE           1126
#define IDC_KUNDAN_PRICE_QUOTE          1127
#define ID_REPORTS_EXPORT_PRICEQUOTATION 32775
#define ID_REPORTS_EXPORT_GRFORM        32779
#define ID_SET_EDIT                     32781
#define ID_SET_DELETE_CURRENT           32783
#define ID_SET_SELECTHIGHLIGHTED        32784
#define ID_SET_DELETE_HIGHLIGHTED       32785
#define ID_SET_SELECTALL                32786
#define ID_SET_DELETE_CHECKED           32787
#define ID_SET_DELETECHECKED_HIGHLIGHTED 32788
#define ID_SET_UNSELECTHIGHLIGHTED      32789
#define ID_SET_UNSELECTALL              32790
#define ID_TREE_CREATENEWSTOCKVOUCHER   32793
#define ID_TREE_CREATENEWEXPORTVOUCHER  32795
#define ID_REPORTS_EXPORT_PACKAGELIST_ORIGINAL 32809
#define ID_REPORTS_EXPORT_PACKAGELIST_SOLD 32810
#define ID_REPORTS_EXPORT_PACKAGELIST_UNSOLD 32811
#define ID_REPORTS_EXPORT_SHORTINVOICE_ORIGINAL 32812
#define ID_REPORTS_EXPORT_SHORTINVOICE_SOLD 32813
#define ID_REPORTS_EXPORT_SHORTINVOICE_UNSOLD 32814
#define ID_REPORTS_EXPORT_TAGS          32817
#define ID_SET_ADDNEW                   32818
#define ID_REPORTS_CATALOGUE            32821
#define ID_UPDATEGOLDRATE               32827
#define ID_MANAGEDESCRIPTIONDATABASE    32828
#define ID_REPORTS_EXPORT_CHECKLIST     32832
#define ID_TREE_DELETESOLDITEMS         32834
#define ID_TREE_REALLOCATESERIALNUMBERS 32836
#define ID_TREE_MARKITEMASSOLD_ONPRODUCTID 32844
#define ID_TREE_MARKITEMASSOLD_ONSERIALNUMBER 32845
#define ID_SET_CHANGEPRODUCTID          32846
#define ID_CHANGEFILEPATH               32847
#define ID_EXPORTSETTINGS               32848
#define ID_IMPORTSETTINGS               32849
#define ID_USINGFOREXPORTS_NATIVECURRENCY 32850
#define ID_USINGFOREXPORTS_DOLLARUSD    32851
#define ID_REPORTS_EXPORT_PHOTOINVOICE_ORIGINAL 32853
#define ID_REPORTS_EXPORT_PHOTOINVOICE_SOLD 32854
#define ID_REPORTS_EXPORT_PHOTOINVOICE_UNSOLD 32855
#define ID_SET_RESETOLDSERIALS          32856
#define ID_TREE_DELETESELECTED          32857
#define ID_TREE_UPDATEINFORMATION       32858
#define ID_PREVIOUS                     32859
#define ID_NEXT                         32860
#define ID_CANCEL                       32862
#define ID_PRINT                        32863
#define ID_SET_MOVE_CREATENEW           32870
#define ID_SET_MOVE_ADDTOEXISTING       32871
#define ID_TREE_CREATENEWKUNDANVOUCHER  32872
#define ID_REPORTS_KUNDAN_STOCKSREPORT_ACTUALS_ORIGINAL 32873
#define ID_REPORTS_KUNDAN_STOCKSREPORT_ACTUALS_SOLD 32874
#define ID_REPORTS_KUNDAN_STOCKSREPORT_ACTUALS_UNSOLD 32875
#define ID_REPORTS_KUNDAN_STOCKSREPORT_MARKED_ORIGINAL 32876
#define ID_REPORTS_KUNDAN_STOCKSREPORT_MARKED_SOLD 32877
#define ID_REPORTS_KUNDAN_STOCKSREPORT_MARKED_UNSOLD 32878
#define ID_REPORTS_KUNDAN_CHECKLIST     32879
#define ID_REPORTS_KUNDAN_TAGS          32880
#define ID_REPORTS_STOCK_CHECKLIST      32887
#define ID_REPORTS_STOCK_TAGS           32888
#define ID_REPORTS_STOCK_STOCKSREPORT_ACTUALS_ORIGINAL 32889
#define ID_REPORTS_STOCK_STOCKSREPORT_ACTUALS_SOLD 32890
#define ID_REPORTS_STOCK_STOCKSREPORT_ACTUALS_UNSOLD 32891
#define ID_REPORTS_STOCK_STOCKSREPORT_MARKED_ORIGINAL 32892
#define ID_REPORTS_STOCK_STOCKSREPORT_MARKED_SOLD 32893
#define ID_REPORTS_STOCK_STOCKSREPORT_MARKED_UNSOLD 32894
#define ID_TREE_QUERYSET_GROSS_WEIGHT   32897
#define ID_TREE_QUERYSET_ID             32898
#define ID_REPORTS_STOCK_PRICEQUOTATION 32899
#define ID_REPORTS_KUNDAN_PRICEQUOTATION 32900
#define ID_SETTINGS_CREATEBACKUP        32901
#define ID_SETTINGS_RESTOREFROMBACKUP   32902

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
